apiVersion: v1
kind: Service
metadata:
  name: "vdc-{{ vdcName }}"
spec:
  type: NodePort
  selector:
    component: "vdc-{{ vdcName }}"
  ports:
  - name: http
    port: 8080
    targetPort: 50003

---
apiVersion: v1
kind: Pod
metadata:
  name: "slalite-{{ vdcName }}"
  labels:
    component: "vdc-{{ vdcName }}"
spec:
  containers:
  - name: slalite
    image: ditas/slalite
    ports:
    - containerPort: 8090
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint

  volumes:
  - name: blueprint
    hostPath:
        path: "/home/{{ ansible_user_id }}/blueprint"
        type: Directory

---
apiVersion: v1
kind: Pod
metadata:
  name: "due-{{ vdcName }}"
  labels:
    component: "vdc-{{ vdcName }}"
spec:
  containers:
  - name: due
    image: ditas/data-utility-evaluator:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint

  volumes:
  - name: blueprint
    hostPath:
        path: "/home/{{ ansible_user_id }}/blueprint"
        type: Directory
  
---
apiVersion: v1
kind: Pod
metadata:
  name: "ideko-{{ vdcName }}"
  labels:
    component: "vdc-{{ vdcName }}"
spec:
  containers:
  - name: ideko-uc
    image: ditas/ideko-use-case:latest
    ports:
    - containerPort: 8080
    - containerPort: 8484
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint

  volumes:
  - name: blueprint
    hostPath:
        path: "/home/{{ ansible_user_id }}/blueprint"
        type: Directory

  