apiVersion: v1
kind: Service
metadata:
  name: "vdc{{ blueprintNumber }}"
spec:
  type: NodePort
  selector:
    component: "vdc{{ blueprintNumber }}"
  ports:
  - name: http
    port: 8080
    targetPort: 50003

---
apiVersion: v1
kind: Pod
metadata:
  name: "vdc{{ blueprintNumber }}"
  labels:
    component: "vdc{{ blueprintNumber }}"
spec:
  containers:
  - name: ds4m
    image: ditas/decision-system-for-data-and-computation-movement
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint

  - name: slalite
    image: ditas/slalite
    ports:
      - containerPort: 8090
    volumeMounts:
      - name: blueprint
        mountPath: /opt/blueprint

  - name: DUE
    image: ditas/data-utility-evaluator:latest
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: blueprint
        mountPath: /opt/blueprint 
         
  - name: ideko-uc
    image: ditas/ideko-use-case:001
    ports:
      - containerPort: 8080
      - containerPort: 8484
    volumeMounts:
      - name: blueprint
        mountPath: /opt/blueprint

  volumes:
  - name: blueprint
    hostPath:
      path: "/home/cloudsigma/blueprint{{ blueprintNumber }}"
      type: Directory