apiVersion: v1
kind: Service
metadata:
  name: "vdm-{{ blueprintId }}"
spec:
  type: NodePort
  selector:
    component: "vdm-{{ blueprintId }}"
  ports:
  - name: http
    port: 8080
    targetPort: 50003

---
apiVersion: v1
kind: Pod
metadata:
  name: "ds4m-{{ blueprintId }}"
  labels:
    component: "vdm-{{ blueprintId }}"
spec:
  containers:
  - name: ds4m
    image: ditas/decision-system-for-data-and-computation-movement
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint

  volumes:
  - name: blueprint
    hostPath:
        path: "/home/{{ ansible_user_id }}/blueprint"
        type: Directory
